apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
  labels:
    app: backend-feed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
      - name: backend-feed
        image: dawitsisay/udagram-api-feed
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        resources: 
          requests:
            memory: "1024Mi"
            cpu: "250m"
          limits:
            memory: "2048Mi"
            cpu: "500m" 
        envFrom:
          - configMapRef:
             name: udagram-env
          - secretRef:
             name: udagramdb-env
        volumeMounts:
          - mountPath: "/root/.aws/"
            name: udagram-aws
      volumes:
        - name: udagram-aws
          configMap:
             name: udagram-aws     